### ISSUE TITLE
Gradle fail (databinding setting?)

### ISSUE THREAD

**Issue by wisien92** [DavidEdwards/mvvm-example#1]
Hi,

I have updated android studio and cloned repo and tried to build project but gradle throws:

> 'other' has different root

From what I have read it can have something to do with dataBinding. 

I am using:
- Kotlin Plugin 1.3.31
- Android Studio 3.4.1

**Comment by DavidEdwards** [comment]
I just cloned the repo and it works fine.

My current environment:

>Android Studio 3.5 Canary 7
>Build #AI-183.5429.30.35.5346365, built on March 1, 2019
>JRE: 1.8.0_152-release-1343-b16-5323222 amd64
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
>Linux 4.18.0-20-generic

I'll close this, but post again if you still have issues after updating.
